Traceback (most recent call last):
  File "/home/velociraptor/raptor_test/test.py", line 1, in <module>
    f = open('test_file.txt', "r+")
FileNotFoundError: [Errno 2] No such file or directory: 'test_file.txt'
